-- Create database and schema.

CREATE DATABASE IF NOT EXISTS WEALTH_RAG_DB;

CREATE SCHEMA IF NOT EXISTS WEALTH_RAG_DB.RAG;

USE DATABASE WEALTH_RAG_DB;
USE SCHEMA RAG;

CREATE WAREHOUSE IF NOT EXISTS RAG_WH
WITH
WAREHOUSE_SIZE='SMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;
