-- Raw extracted documents

CREATE OR REPLACE TABLE RAW_DOCUMENTS
(
    DOC_ID NUMBER AUTOINCREMENT,
    DOC_NAME STRING,
    DOC_TEXT STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Document chunks

CREATE OR REPLACE TABLE DOCUMENT_CHUNKS
(
    DOC_ID NUMBER,
    DOC_NAME STRING,
    CHUNK_ID NUMBER,
    CHUNK_TEXT STRING,
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Vector store

CREATE OR REPLACE TABLE VECTOR_STORE
(
    DOC_ID NUMBER,
    DOC_NAME STRING,
    CHUNK_ID NUMBER,
    CHUNK_TEXT STRING,
    EMBEDDING VECTOR(FLOAT,768),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
